/* MOSTRAR DADOS */
SELECT * FROM aluno;

SELECT * FROM materia;

/*MOSTRAR DADOS EM UMA "BUSCA" COM LIKE  -- % ENTRE AS ASPAS */
SELECT * FROM aluno WHERE Nome LIKE '%Bruna%'

/* ORDENAR POR NOME DO ALUNO DE FORMA ASCENDENTE */
SELECT * FROM aluno ORDER BY Nome ASC;

/* ORDENAR POR NOME DO ALUNO DE FORMA DECRESCENTE */
SELECT * FROM aluno ORDER BY Nome DESC;